Anem a practicar i a familiaritzar-nos amb l'estructura de Matrius, dimensió, forma, vectorització i Broadcasting .

 ### Nivell 1 ⭐️

Treballem els conceptes de l'estructura d'una matriu, dimensió, eixos i la vectorització que ens permet reduir l'ús de for loops en operacions aritmètiques o matemàtiques..

## Exercici 1 

Crea un np.array d'una dimensió, que inclogui l'almenys 8 nombres sencers, data type int64. Mostra la dimensió i la forma de la matriu. .



In [51]:
import numpy as np
nombres = np.array([1, 2, 3, 4, 5, 6, 7, 8], dtype = 'int64', ndmin = 1)
print(nombres)
print(nombres.dtype)
print(nombres.shape)


[1 2 3 4 5 6 7 8]
int64
(8,)


## Exercici 2 

De la matriu de l'exercici 1, calcula el valor mitjà dels valors introduïts i resta la mitjana resultant de cada un dels valors de la matriu.

In [32]:
x = np.mean(nombres)
print(x)
new_nombres = nombres - x
print(new_nombres)

4.5
[-3.5 -2.5 -1.5 -0.5  0.5  1.5  2.5  3.5]


## Exercici 3

Crea una matriu bidimensional amb una forma de 5 x 5. Extreu el valor màxim de la matriu, i els valors màxims de cadascun dels seus eixos.



In [50]:
import numpy as np

m2D = np.array([[5, 4, 7, 7, 3], [9, 7, 3, 9, 8], [4, 6, 6, 5, 9], [6, 7, 6 , 5, 4], [7, 3, 9, 8, 8]], ndmin=2)
print(m2D)

print("El valor màxim de la matriu es", np.amax(m2D))
print("El valor màxim de l'eix vertical es", np.amax(m2D, axis = 0))
print("El valor màxim de l'eix horitzontal es", np.amax(m2D, axis = 1))




[[5 4 7 7 3]
 [9 7 3 9 8]
 [4 6 6 5 9]
 [6 7 6 5 4]
 [7 3 9 8 8]]
El valor màxim de la matriu es 9
El valor màxim de l'eix vertical es [9 7 9 9 9]
El valor màxim de l'eix horitzontal es [7 9 9 7 9]


 ### Nivell 2  ⭐️⭐️

## Exercici 4

## Exercici 5

## Exercici 6

## Exercici 7

 ### Nivell 3 ⭐️⭐️⭐️

## Exercici 8